In [1]:
import numpy as np


In [2]:
x=np.array([1,2,3,4,5])

In [3]:
y=np.arange(5)

In [4]:
y

array([0, 1, 2, 3, 4])

In [5]:
z=x+y

In [6]:
z

array([1, 3, 5, 7, 9])

In [7]:
z*2

array([ 2,  6, 10, 14, 18])

In [8]:
z**2

array([ 1,  9, 25, 49, 81])

In [13]:
c=np.array([34,45,67,45,20,40])

In [14]:
v=c>=40

In [15]:
v

array([False,  True,  True,  True, False,  True])

In [16]:
x=np.array([1,2,3,4,5,6,7])

In [17]:
x.sum()

28

In [18]:
x.min()

1

In [19]:
x.max()

7

In [20]:
np.power(x,3)

array([  1,   8,  27,  64, 125, 216, 343])

In [21]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [22]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[1,50,3],[40,5,6],[7,80,9]])

In [26]:
np.concatenate([x,y],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1, 50,  3],
       [40,  5,  6],
       [ 7, 80,  9]])

In [27]:
np.concatenate([x,y],axis=1)

array([[ 1,  2,  3,  1, 50,  3],
       [ 4,  5,  6, 40,  5,  6],
       [ 7,  8,  9,  7, 80,  9]])

In [28]:
a=np.arange(8)

In [31]:
np.split(a,2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

# split with position indicate

In [32]:
np.split(a,[3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [34]:
f=np.arange(20).reshape(4,5)

In [35]:
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
np.vsplit(f,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [39]:
np.hsplit(f,5)

[array([[ 0],
        [ 5],
        [10],
        [15]]), array([[ 1],
        [ 6],
        [11],
        [16]]), array([[ 2],
        [ 7],
        [12],
        [17]]), array([[ 3],
        [ 8],
        [13],
        [18]]), array([[ 4],
        [ 9],
        [14],
        [19]])]

In [40]:
c=np.arange(16).reshape(4,4)

In [42]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]