In [1]:
import numpy as np

In [2]:
array0=np.array([[1,2,3],[4,5,6],[121,134,145]])

In [4]:
array0[:,1]

array([  2,   5, 134])

In [26]:
array0[1 :,0 : 2]

array([[  4,   5],
       [121, 134]])

In [27]:
array0[2 : ,]

array([[121, 134, 145]])

In [6]:
array0[0,2]

3

In [10]:
array1=np.array([[[1,2,3,4],[2,3,4],[5,6,7]]])

<ipython-input-10-38ed099b69a1>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1=np.array([[[1,2,3,4],[2,3,4],[5,6,7]]])


In [11]:
array1.ndim

2

In [13]:
array1[:,1]

array([list([2, 3, 4])], dtype=object)

In [14]:
array2=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]],[[10,20,30],[10,20,30]]])

In [16]:
array2.ndim

3

In [28]:
array2[1 :,]

array([[[ 8,  9, 10],
        [11, 12, 13]],

       [[10, 20, 30],
        [10, 20, 30]]])

In [20]:
array2[1]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [21]:
array2[0 : 2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [24]:
array2[-1 :  ]

array([[[10, 20, 30],
        [10, 20, 30]]])